# Generated by Django 4.2 on 2024-03-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 13, 22, 28, 424375)),
        ),
    ]
