# Generated by Django 4.2 on 2024-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_taskactivity_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
